=== joeha480/dotify.task.impl/src/org/daisy/dotify/tasks/impl/input/xml/docx/tagsets/tagset.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" targetNamespace="http://www.tpb.se/ns/2006/wml2dtbook" elementFormDefault="qualified">
	<xs:element name="character">
		<xs:annotation>
			<xs:documentation>Contains all character styles that should be addressed</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tag" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Defines a style</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:group ref="cTagChoice"/>
						<xs:attribute name="name" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Defines the style name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="useInlineFormatting" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="comment" type="xs:string">
		<xs:annotation>
			<xs:documentation>Defines that the style should become a comment</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="custom">
		<xs:annotation>
			<xs:documentation>Defines a set of customized rules</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paragraphs"/>
				<xs:element ref="character"/>
			</xs:sequence>
			<xs:attribute name="style" type="xs:ID" use="required">
				<xs:annotation>
					<xs:documentation>Identifies this custom set</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="map">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="attribute"/>
			</xs:sequence>
			<xs:attributeGroup ref="value"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mappings">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="standardWord" maxOccurs="unbounded"/>
				<xs:element ref="custom" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="version" type="xs:string" use="required" fixed="2006-1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="noteref" type="xs:string">
		<xs:annotation>
			<xs:documentation>Defines</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="pagenum" type="xs:string">
		<xs:annotation>
			<xs:documentation>Defines</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="paragraphs">
		<xs:annotation>
			<xs:documentation>Contains all paragraph styles that should be addressed</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tag" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Defines a style</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:group ref="pTagChoice"/>
						<xs:attribute name="name" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Defines the style name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="listOverride" type="xs:boolean" use="optional" default="false"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="standardWord">
		<xs:annotation>
			<xs:documentation>Defines a set of default mappings to built-in Word styles</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paragraphs"/>
				<xs:element ref="character"/>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:annotation>
					<xs:documentation>Defines the version of the built-in tag set</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:group name="cTagChoice">
		<xs:choice>
			<xs:element ref="map"/>
			<xs:element ref="pagenum"/>
			<xs:element ref="noteref"/>
			<xs:element ref="comment"/>
		</xs:choice>
	</xs:group>
	<xs:group name="pTagChoice">
		<xs:choice>
			<xs:element ref="map"/>
			<xs:element ref="wrap"/>
			<xs:element ref="comment"/>
		</xs:choice>
	</xs:group>
	<xs:element name="wrap">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence>
					<xs:element ref="using"/>
				</xs:sequence>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="attribute"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="value" type="xs:NMTOKEN" use="required">
				<xs:annotation>
					<xs:documentation>Defines the tag to wrap with</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="addId" use="required">
				<xs:annotation>
					<xs:documentation>Defines if a unique id should be added to this tag</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="merge" use="required">
				<xs:annotation>
					<xs:documentation>Defines if consecutive styles should be merged within the same wrapping tag</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:annotation>
			<xs:documentation>Defines attributes that should be added to the wrapping tag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Defines the value</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required">
				<xs:annotation>
					<xs:documentation>Defines the name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="using">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="attribute"/>
			</xs:sequence>
			<xs:attributeGroup ref="value"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="value">
		<xs:attribute name="value" type="xs:NMTOKEN" use="required">
			<xs:annotation>
				<xs:documentation>Defines the value</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
</xs:schema>

=== joeha480/dotify.task.impl/src/org/daisy/dotify/tasks/impl/input/xml/docx/tagsets/custom-tagset.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings version="2006-1" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tpb.se/ns/2006/wml2dtbook tagset.xsd">
	<custom style="default">
		<paragraphs>
			<tag name="example">
				<map value="p"/>
			</tag>
		</paragraphs>
		<character useInlineFormatting="true"/>
	</custom>
	<custom style="native">
		<paragraphs>
			<!-- New template -->
			<tag name="Address (DAISY)">
				<map value="line">
					<attribute name="group" value="address"/>
				</map>
			</tag>
			<tag name="Author (DAISY)">
				<map value="author"/>
			</tag>
			<tag name="Blockquote (DAISY)">
				<map value="p">
					<attribute name="group" value="blockquote"/>
				</map>
			</tag>
			<tag name="Blockquote - Author (DAISY)">
				<map value="author">
					<attribute name="group" value="blockquote"/>
				</map>
			</tag>
			<tag name="Bridgehead (DAISY)">
				<map value="bridgehead"/>
			</tag>
			<tag name="Byline (DAISY)">
				<map value="byline"/>
			</tag>
			<tag name="Covertitle (DAISY)">
				<map value="covertitle"/>
			</tag>
			<tag name="Dateline (DAISY)">
				<map value="dateline"/>
			</tag>
			<tag name="Epigraph (DAISY)">
				<map value="p">
					<attribute name="group" value="epigraph"/>
				</map>
			</tag>
			<tag name="Epigraph - Author (DAISY)">
				<map value="author">
					<attribute name="group" value="epigraph"/>
				</map>
			</tag>
			<tag name="Poem (DAISY)">
				<map value="line">
					<attribute name="group" value="poem"/>
				</map>
			</tag>
			<tag name="Poem - Author (DAISY)">
				<map value="author">
					<attribute name="group" value="poem"/>
				</map>
			</tag>
			<tag name="Poem - Byline (DAISY)">
				<map value="byline">
					<attribute name="group" value="poem"/>
				</map>
			</tag>
			<tag name="Poem - Heading (DAISY)">
				<map value="hd">
					<attribute name="group" value="poem"/>
				</map>
			</tag>
			<tag name="Poem - Title (DAISY)">
				<map value="title">
					<attribute name="group" value="poem"/>
				</map>
			</tag>
			<tag name="Prodnote - Optional (DAISY)">
				<map value="p">
					<attribute name="group" value="prodnote-optional"/>
				</map>
			</tag>
			<tag name="Prodnote - Required (DAISY)">
				<map value="p">
					<attribute name="group" value="prodnote-required"/>
				</map>
			</tag>
			<!-- / New template -->
		</paragraphs>
		<character useInlineFormatting="true">
			<!-- New template -->
			<tag name="Citation (DAISY)">
				<map value="cite"/>
			</tag>
			<tag name="Code (DAISY)">
				<map value="code"/>
			</tag>
			<tag name="Definition (DAISY)">
				<map value="dfn"/>
			</tag>
			<tag name="Keyboard Input (DAISY)">
				<map value="kbd"/>
			</tag>
			<tag name="Page Number (DAISY)">
				<pagenum/>
			</tag>
			<tag name="Quotation (DAISY)">
				<map value="q"/>
			</tag>
			<tag name="Sample (DAISY)">
				<map value="samp"/>
			</tag>
			<!-- / New template -->
		</character>
	</custom>
	<custom style="scanned">
		<paragraphs>
			<tag name="example">
				<map value="p"/>
			</tag>
			<tag name="footnote text">
				<!--
				<wrap value="note" addId="true" merge="false">
					<using value="p"/>
				</wrap>-->
				<map value="p">
					<attribute name="group" value="note"/>
				</map>
			</tag>
		</paragraphs>
		<character useInlineFormatting="true">
			<tag name="footnote reference"><noteref/></tag>
		</character>
	</custom>
</mappings>

=== joeha480/dotify.task.impl/src/org/daisy/dotify/tasks/impl/input/xml/docx/tagsets/default-tagset.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings version="2006-1" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tpb.se/ns/2006/wml2dtbook tagset.xsd">
	<standardWord version="4">
		<paragraphs>
			<tag name="heading 1" listOverride="true"><map value="h1"/></tag>
			<tag name="heading 2" listOverride="true"><map value="h2"/></tag>
			<tag name="heading 3" listOverride="true"><map value="h3"/></tag>
			<tag name="heading 4" listOverride="true"><map value="h4"/></tag>
			<tag name="heading 5" listOverride="true"><map value="h5"/></tag>
			<tag name="heading 6" listOverride="true"><map value="h6"/></tag>
			<tag name="Block Text">
				<map value="p">
					<attribute name="group" value="blockquote"/>
				</map>
			</tag>
			<tag name="caption">
				<map value="caption">
					<attribute name="group" value="imggroup"/>
				</map>
			</tag>
			<tag name="list">
				<map value="li"/>
			</tag>
			<!-- Added for Word 2007 -->
			<tag name="List">
				<map value="li">
					<attribute name="group" value="p-list"/>
				</map>
			</tag>
			<!--
			<tag name="List Number" listOverride="true">
				<wrap value="list" addId="false" merge="true">
					<using value="li"/>
					<attribute name="type" value="ol"/>
				</wrap>
			</tag>
			<tag name="List Bullet" listOverride="true">
				<wrap value="list" addId="false" merge="true">
					<using value="li"/>
					<attribute name="type" value="ul"/>
				</wrap>
			</tag>-->
		</paragraphs>
		<character>
			<tag name="HTML Cite">
				<map value="cite"/>
			</tag>
			<tag name="HTML Code">
				<map value="code"/>
			</tag>
			<tag name="HTML Definition">
				<map value="dfn"/>
			</tag>
			<tag name="HTML Keyboard">
				<map value="kbd"/>
			</tag>
			<tag name="HTML Sample">
				<map value="samp"/>
			</tag>
			<tag name="Strong"><map value="strong"/></tag>
			<tag name="Emphasis"><map value="em"/></tag>
			<tag name="page number"><pagenum/></tag>
		</character>
	</standardWord>
</mappings>
